name: veshell
description: A command-line application that help dev veshell .
version: 1.0.0
repository: https://github.com/free-explorers/veshell

executables:
  veshell: veshell

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  ansicolor: ^2.0.2
  args: ^2.4.2
  path: ^1.8.3
  
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
