blank_issues_enabled: false
contact_links:
  - name: Chat on Discord 
    url: https://discord.gg/vBb7D9a
    about: Join the Free Explorers Discord
  - name: Support the project & become one of us
    url: https://opencollective.com/free-explorers
    about: Join the Free Explorers collective