targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          - lib/**/provider/**.dart
          - lib/**/model/**.serializable.dart
          
      freezed|freezed:
        enabled: true
        generate_for:
          - lib/**/model/**.dart
          
      json_serializable:
        options:
          any_map: true
          explicit_to_json: true
          
global_options:
  freezed:
    runs_before:
      - json_serializable
      - riverpod_generator
 
  json_serializable:
    runs_before:
      - riverpod_generator